root_path: C:/Users/joojn/Documents/Fortnite Projects/MinerSimulator/Plugins/MinerSimulator/Content/Screens

use_lang: false
lang_path: C:/Users/joojn/Documents/Fortnite Projects/MinerSimulator/Plugins/MinerSimulator/Content/Lang.verse

override_screens:
  - name: ShopWeapons
    path: ./Shop/ShopWeapons.verse 

  - name: ShopHitEffects
    path: ./Shop/ShopHitEffects.verse

  - name: ShopUpgrades
    path: ./Shop/ShopUpgrades.verse

  - name: GemShopEggs
    path: ./Shop/GemShop.verse