root_path: C:/Users/joojn/Documents/Fortnite Projects/HTycoon/Plugins/HTycoon/Content

use_lang: false
lang_path: ''

override_screens:
  - name: MagicBook
    path: ./Screens/MagicBook.verse

  - name: Rewards
    path: ./TycoonFeatures/PlaytimeRewards.verse